### ISSUE TITLE
Unable to extract images from IG Stories

### ISSUE THREAD

**Issue by Orudeon** [theus/instantgram#12]
![chrome_2018-11-24_09-57-32](https://user-images.githubusercontent.com/16169101/48971504-64033280-efcf-11e8-81d3-9e5e0a085093.png)
Attached is the error I get when I try grabbing images from an IG story. Videos still work. Grabbing images using the network data tab in Chrome's console also still works. It's difficult to link an IG Story for testing since they only last for 24 hours.

**Comment by theus** [comment]
@Orudeon sorry for the late response. You're still with this bug yet? I was testing here and it's ok.

**Comment by Orudeon** [comment]
Yeah, I'm still having the issue as of a few moments ago when I tested it again. Is there a new version that fixes it? I'm not sure how to diagnose what's actually going on.

**Comment by theus** [comment]
Delete the actual bookmark and get a new on https://theus.github.io/instantgram/. I think that this is already resolved. And the "update notification" isn't available because of this issue #10

**Comment by Orudeon** [comment]
I just replaced the bookmark with the one from there and it doesn't seem to have impacted anything

**Comment by theus** [comment]
I tested with stories of https://www.instagram.com/judaocombr/ (is a pop news profile, so always has stories) and worked well as this video https://gfycat.com/IncompatibleSomeImperatorangel

**Comment by Orudeon** [comment]
I just deleted the bookmark, restarted chrome, bookmarked again, and ctrl-refreshed instagram and it's still happening, including on judaocombr.  I don't get it

**Comment by theus** [comment]
So strange 🤔 . Open the console before run [instantgram] and run it. Has some error related?

**Comment by Orudeon** [comment]
run [instantgram]
VM492:1 Uncaught ReferenceError: run is not defined
    at <anonymous>:1:1
(anonymous) @ VM492:1
run [instantgram]
VM512:1 Uncaught ReferenceError: run is not defined
    at <anonymous>:1:1
(anonymous) @ VM512:1
b9af5bda8fd7.js?control=1:1 POST https://graph.instagram.com/logging_client_events net::ERR_BLOCKED_BY_CLIENT
o.send @ b9af5bda8fd7.js?control=1:1
(anonymous) @ b9af5bda8fd7.js?control=1:1
(anonymous) @ b9af5bda8fd7.js?control=1:1
m.map @ b9af5bda8fd7.js?control=1:1
map @ b9af5bda8fd7.js?control=1:1
(anonymous) @ b9af5bda8fd7.js?control=1:1
e @ b9af5bda8fd7.js?control=1:1
b @ b9af5bda8fd7.js?control=1:1
t.post @ b9af5bda8fd7.js?control=1:1
t.send @ b9af5bda8fd7.js?control=1:1
send @ b9af5bda8fd7.js?control=1:1
z @ b9af5bda8fd7.js?control=1:1
w.a.guard.isContinuation @ b9af5bda8fd7.js?control=1:1
setTimeout (async)
B @ b9af5bda8fd7.js?control=1:1
z @ b9af5bda8fd7.js?control=1:1
w.a.guard.isContinuation @ b9af5bda8fd7.js?control=1:1
setTimeout (async)
B @ b9af5bda8fd7.js?control=1:1
K @ b9af5bda8fd7.js?control=1:1
r @ b9af5bda8fd7.js?control=1:1
b9af5bda8fd7.js?control=1:1 POST https://graph.instagram.com/logging_client_events net::ERR_BLOCKED_BY_CLIENT
o.send @ b9af5bda8fd7.js?control=1:1
(anonymous) @ b9af5bda8fd7.js?control=1:1
(anonymous) @ b9af5bda8fd7.js?control=1:1
m.map @ b9af5bda8fd7.js?control=1:1
map @ b9af5bda8fd7.js?control=1:1
(anonymous) @ b9af5bda8fd7.js?control=1:1
e @ b9af5bda8fd7.js?control=1:1
b @ b9af5bda8fd7.js?control=1:1
t.post @ b9af5bda8fd7.js?control=1:1
t.send @ b9af5bda8fd7.js?control=1:1
send @ b9af5bda8fd7.js?control=1:1
z @ b9af5bda8fd7.js?control=1:1
w.a.guard.isContinuation @ b9af5bda8fd7.js?control=1:1
setTimeout (async)
B @ b9af5bda8fd7.js?control=1:1
K @ b9af5bda8fd7.js?control=1:1
r @ b9af5bda8fd7.js?control=1:1
run [instantgram]
VM670:1 Uncaught ReferenceError: run is not defined
    at <anonymous>:1:1
(anonymous) @ VM670:1
VM671:1 [instantgram] set language: undefined 
 For more information about available languages please check http://theus.github.io/instantgram
VM671:1 [instantgram] is looking for available updates…
VM671:1 Refused to connect to 'https://theus.github.io/instantgram/package.json' because it violates the following Content Security Policy directive: "connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd".

t.default @ VM671:1
(anonymous) @ VM671:1
a @ VM671:1
(anonymous) @ VM671:1
(anonymous) @ VM671:1
(anonymous) @ VM671:1
VM671:1 [instantgram] is looking for available updates…
VM672:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous> (<anonymous>:1:10258)
(anonymous) @ VM671:1
XMLHttpRequest.send (async)
t.default @ VM671:1
(anonymous) @ VM671:1
a @ VM671:1
(anonymous) @ VM671:1
(anonymous) @ VM671:1
(anonymous) @ VM671:1
b9af5bda8fd7.js?control=1:1 POST https://graph.instagram.com/logging_client_events net::ERR_BLOCKED_BY_CLIENT
t.sendWithBeacon @ b9af5bda8fd7.js?control=1:1
sendWithBeacon @ b9af5bda8fd7.js?control=1:1
V @ b9af5bda8fd7.js?control=1:1
(anonymous) @ b9af5bda8fd7.js?control=1:1
r @ b9af5bda8fd7.js?control=1:1
b9af5bda8fd7.js?control=1:1 POST https://graph.instagram.com/logging_client_events net::ERR_BLOCKED_BY_CLIENT


I don't know what any of this means or even if I did what I'm supposed to do, and it looks incredibly messy.

**Comment by theus** [comment]
Sorry for this @Orudeon. I mean open the console and just click in [instantgram] bookmarklet.

**Comment by Orudeon** [comment]
[instantgram] set language: undefined 
 For more information about available languages please check http://theus.github.io/instantgram
![chrome_2018-12-05_15-54-18](https://user-images.githubusercontent.com/16169101/49551916-18da0100-f8a6-11e8-9f57-7b44c0ead281.png)
I get these errors fairly consistently when I click Instantgram on a story photo.
![chrome_2018-12-05_15-57-29](https://user-images.githubusercontent.com/16169101/49552003-7cfcc500-f8a6-11e8-8ef0-44f78bcb2222.png)
I also get this error (and similar ones) periodically when not doing anything at all. It's difficult to determine if they're all identical because there's so much gibberish to sift through

**Comment by theus** [comment]
Here has the same errors. The only thing that I noticed that is different is _[instantgram] set language: undefined_

![image](https://user-images.githubusercontent.com/61322/49552435-5d7b9180-f8d2-11e8-982d-7bdcbeb6ed04.png)

These errors is because Instagram is blocking request to outside theirs "secure domains", so [instagram] can't connect with github page to determine it's version.

In theory, this context doesn't break the bookmarklet system. Sometimes Instagram rollup different versions to part of users. In this case, could break up [instantgram] 🤷‍♂️

**Comment by Orudeon** [comment]
Aw man, so I guess we have to wait until we're running the same internal version of instagram's code or something?

**Comment by theus** [comment]
I think so! I'll let this issue open until we got more information.

**Comment by nightputting** [comment]
I am getting some errors again when trying to open pictures that are on pages. "Ops, did you open any Instagram post? Like for example instagram.com/p/82jd828jd" Anything I can do to fix? It's only on certain posts, but there is no pattern.

**Comment by theus** [comment]
I'll close this issue. If necessary, we'll open again.
